#!/bin/sh
printf 'Status: 302 Found\r\n'
printf 'Location: /cgi-bin/luci/admin/services/wifi-clients\r\n'
printf 'Content-Type: text/plain; charset=utf-8\r\n'
printf '\r\n'
printf 'Redirecting to LuCI WiFi Clients...\n'
