include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI temperature history page for ZBT-Z8803BE
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+sms-tool_q

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=openrt-zbt8803be

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
