include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI speed test page
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+python3
LUCI_BUILD_PACKAGES:=$(PKG_NAME)

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=openrt-zbt8803be

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
