include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI modem event history page for ZBT-Z8803BE
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+qmodem +qmodem_monitor

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=openrt-zbt8803be

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
